<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20220728183700" tests="1" file="unittest/loader.py" time="0.000" timestamp="2022-07-28T18:37:00" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="newtourTest" time="0.000" timestamp="2022-07-28T18:37:00" file="..\..\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py" line="33">
		<error type="ImportError" message="Failed to import test module: newtourTest
Traceback (most recent call last):
  File &quot;C:\Users\edgar.velazquez\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;C:\Users\edgar.velazquez\PycharmProjects\Practice_pro\newtourTest.py&quot;, line 4, in &lt;module&gt;
    import output as output
ModuleNotFoundError: No module named 'output'
"><![CDATA[ImportError: Failed to import test module: newtourTest
Traceback (most recent call last):
  File "C:\Users\edgar.velazquez\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\edgar.velazquez\PycharmProjects\Practice_pro\newtourTest.py", line 4, in <module>
    import output as output
ModuleNotFoundError: No module named 'output'

]]></error>
	</testcase>
</testsuite>
